// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVNBH6lYYYES4wPANRUN1pkdvPD9V-Tc',
    appId: '1:187157161217:web:d0a1cb32b909012f696700',
    messagingSenderId: '187157161217',
    projectId: 'fire-management-iste',
    authDomain: 'fire-management-iste.firebaseapp.com',
    databaseURL: 'https://fire-management-iste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-management-iste.firebasestorage.app',
    measurementId: 'G-PMDR6N8EZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEFjrrSnDr0bHfNOb_AMxmw98DDt4FwPg',
    appId: '1:187157161217:android:130316ca94729b19696700',
    messagingSenderId: '187157161217',
    projectId: 'fire-management-iste',
    databaseURL: 'https://fire-management-iste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-management-iste.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUaMDb_crhOupns7HsnZTwKT9pPQhAN0',
    appId: '1:187157161217:ios:656f4be0d0611527696700',
    messagingSenderId: '187157161217',
    projectId: 'fire-management-iste',
    databaseURL: 'https://fire-management-iste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-management-iste.firebasestorage.app',
    iosBundleId: 'com.example.fireManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqUaMDb_crhOupns7HsnZTwKT9pPQhAN0',
    appId: '1:187157161217:ios:656f4be0d0611527696700',
    messagingSenderId: '187157161217',
    projectId: 'fire-management-iste',
    databaseURL: 'https://fire-management-iste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-management-iste.firebasestorage.app',
    iosBundleId: 'com.example.fireManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfVNBH6lYYYES4wPANRUN1pkdvPD9V-Tc',
    appId: '1:187157161217:web:b599e7bc8868a768696700',
    messagingSenderId: '187157161217',
    projectId: 'fire-management-iste',
    authDomain: 'fire-management-iste.firebaseapp.com',
    databaseURL: 'https://fire-management-iste-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fire-management-iste.firebasestorage.app',
    measurementId: 'G-F1G0SHH7K2',
  );
}
